services:
  # PostgreSQL Database
  - type: pserv
    name: urnav-db
    env: postgresql
    plan: free
    region: oregon
    ipAllowList: []
    
  # FastAPI Backend
  - type: web
    name: urnav-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urnav-db
          property: connectionString
      - key: FOURSQUARE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /docs
    autoDeploy: true
